### ISSUE TITLE
(suggestion) Language to English

### ISSUE THREAD

**Issue by SpreeHertz** [anydown/anydown-next#7]
# Change Language to English
Can you please change to English or implement a translator?

**Comment by hashrock** [comment]
Yeah, We certainly need i18n.

**Comment by hashrock** [comment]
Now UI and the example are written in English.

https://anydown-canary.netlify.app/

![image](https://user-images.githubusercontent.com/3132889/161396427-7237b154-ac3f-4eec-8d7d-1abad548fd89.png)
